name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --build-arg VERSION="$ENV:Version" --build-arg ZIP_URL="http://nginx-win.ecsds.eu/download/nginx%20$ENV:Version.zip" -t nginx-win-servercore .
      env:
        Version: "1.25.4.2%20SnapDragonfly"
