name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --build-arg VERSION="$Version" --build-arg ZIP_URL="http://nginx-win.ecsds.eu/download/nginx%20$Version%20SnapDragonfly.zip" -t nginx-win-servercore .
      env:
        Version: 1.25.4.1
